package com.rnpack.location

object Constants {
  const val RN_PACK_NAME = "@rnpack/location"

  const val RN_PACK_PREFIX = "RN_PACK"

  const val LOG_TAG = RN_PACK_NAME

  const val LOCATION_FOREGROUND_SERVICE_NOTIFICATION_CHANNEL_ID =
    "RN_PACK_LOCATION_FOREGROUND_SERVICE_NOTIFICATION_CHANNEL_ID"

  const val LOCATION_FOREGROUND_SERVICE_BROADCAST_NAME =
    "${BuildConfig.LIBRARY_PACKAGE_NAME}.FOREGROUND_SERVICE_LOCATION_UPDATE_BROADCAST"
  const val FOREGROUND_LOCATION_HEADLESS_JS_TASK_SERVICE_NAME =
    "${RN_PACK_PREFIX}_FOREGROUND_LOCATION_HEADLESS_JS_TASK_SERVICE"

  const val LOCATION_BACKGROUND_SERVICE_BROADCAST_NAME =
    "${BuildConfig.LIBRARY_PACKAGE_NAME}.BACKGROUND_SERVICE_LOCATION_UPDATE_BROADCAST"
  const val BACKGROUND_LOCATION_HEADLESS_JS_TASK_SERVICE_NAME =
    "${RN_PACK_PREFIX}_BACKGROUND_LOCATION_HEADLESS_JS_TASK_SERVICE"

  const val FOREGROUND_LOCATION_SERVICE_NOTIFICATION_ID = 1

  const val LOCATION_PERMISSION_REQ_CODE = 1000

  const val BACKGROUND_LOCATION_WORKER_CONFIGURATION_KEY =
    "BACKGROUND_LOCATION_WORKER_CONFIGURATION_KEY"
}
